#pragma once
enum class ObserverEvent
{
	// NoiseGenerator
	INCREASE_SEED,
	DECREASE_SEED,
	INCREASE_LACUNARITY,
	DECREASE_LACUNARITY,
	INCREASE_OCTAVES,
	DECREASE_OCTAVES,
	INCREASE_PERSISTENCE,
	DECREASE_PERSISTENCE,
	INCREASE_SCALE,
	DECREASE_SCALE,

	// Procedural Generator
	REBUILD_LANDSCAPE,

	INCREASE_XRES,
	DECREASE_XRES,
	INCREASE_ZRES,
	DECREASE_ZRES,
	INCREASE_FALLOFSIZE,
	DECREASE_FALLOFSIZE, 
	INCREASE_SEALEVEL,
	DECREASE_SEALEVEL,
	CHANGE_TYPE_TO_NONE,
	CHANGE_TYPE_TO_CIRCULAR,
	CHANGE_TYPE_TO_ROUNDEDSQUARE
};

class Observer
{
	public:
		virtual ~Observer() {}
		virtual void onNotify(ObserverEvent event) = 0;
};